version: '3.8'

services:
  planner-estudos:
    image: nginx:alpine
    container_name: planner_analista
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
    environment:
      - TZ=America/Sao_Paulo